export interface Table {
  title: string;
  isVisible: boolean;
  valueType: 'number' | 'date' | 'string';
  digitsInfo?: string;
  dateFormat?: string;
  showSort: boolean;
  sortFn: (a: number, b: number) => number;
  sortOrder: string;
  sortDirections: ('ascend' | 'descend' | null)[];
  showFilter: boolean;
  headerEllipsis: boolean;
  breakWord: boolean;
  headerAlign: string;
  width: string;
  columnKey: string;
  cellAlign: string;
  cellEllipsis: boolean;
}
export const arbitragesTableConstant: Table[] = [
  {
    title: 'Buy order Id',
    isVisible: false,
    valueType: 'string',
    showSort: false,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'buyOrderId',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Sell order Id',
    isVisible: false,
    valueType: 'string',
    showSort: false,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'sellOrderId',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Profit',
    isVisible: true,
    valueType: 'number',
    digitsInfo: '1.2-8',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'profit',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Profit (USDT)',
    isVisible: true,
    valueType: 'number',
    digitsInfo: '1.2-8',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'profitUsdt',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Left Over Base',
    isVisible: true,
    valueType: 'string',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'leftOverBase',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Created At Cycle',
    isVisible: false,
    valueType: 'string',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'createdAtCycle',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Status',
    isVisible: true,
    valueType: 'string',
    showSort: false,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'status',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Created At',
    isVisible: true,
    valueType: 'date',
    dateFormat: 'yy/M/d H:mm:s',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'createdAt',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Buy Placed At',
    isVisible: true,
    valueType: 'date',
    dateFormat: 'yy/M/d H:mm:s',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'buyPlacedAt',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Sell Placed At',
    isVisible: true,
    valueType: 'date',
    dateFormat: 'yy/M/d H:mm:s',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'sellPlacedAt',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Buy Filled At',
    isVisible: true,
    valueType: 'date',
    dateFormat: 'yy/M/d H:mm:s',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'buyFilledAt',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Buy Canceled At',
    isVisible: true,
    valueType: 'date',
    dateFormat: 'yy/M/d H:mm:s',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'buyCanceledAt',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Sell Filled At',
    isVisible: true,
    valueType: 'date',
    dateFormat: 'yy/M/d H:mm:s',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'sellFilledAt',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Sell Canceled At',
    isVisible: true,
    valueType: 'date',
    dateFormat: 'yy/M/d H:mm:s',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'sellCanceledAt',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Currency Base',
    isVisible: true,
    valueType: 'string',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'currencyBase',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Buy Target',
    isVisible: true,
    valueType: 'number',
    digitsInfo: '1.2-8',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'buyTarget',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Buy Volume',
    isVisible: true,
    valueType: 'number',
    digitsInfo: '1.2-8',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'buyVolume',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Buy Total (USDT)',
    isVisible: true,
    valueType: 'number',
    digitsInfo: '1.2-8',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'buyTotalUsdt',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Sell Target',
    isVisible: true,
    valueType: 'number',
    digitsInfo: '1.2-8',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'sellTarget',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Sell Volume',
    isVisible: true,
    valueType: 'number',
    digitsInfo: '1.2-8',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'sellVolume',
    cellAlign: 'center',
    cellEllipsis: true
  },
  {
    title: 'Sell Total (USDT)',
    isVisible: true,
    valueType: 'number',
    digitsInfo: '1.2-8',
    showSort: true,
    sortFn: (a: number, b: number) => a - b,
    sortOrder: 'descend',
    sortDirections: ['ascend', 'descend', null],
    showFilter: false,
    headerEllipsis: false,
    breakWord: true,
    headerAlign: 'center',
    width: '48',
    columnKey: 'sellTotalUsdt',
    cellAlign: 'center',
    cellEllipsis: true
  }
];
